name: OpenAI Code Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 🔧 Install Dependencies
        run: pip install openai

      - name: 🤖 Run Azure OpenAI Code Scanner
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI_API_DEPLOYMENT_NAME: ${{ secrets.OPENAI_API_DEPLOYMENT_NAME }}
        run: |
          python .github/scripts/scan_with_openai.py . --output openai_code_scan_report.txt

      - name: 📤 Upload Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: openai-scan-report
          path: openai_code_scan_report.txt
